#spring.application.name=automobileshop
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/automobileshop"
    username: bibhu
    password: bibhu
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
